# info
site_name: Following Cynthia
site_author: Cynthia
site_description: A blog for Cynthia
site_url: 'https://whocarscynthia.github.io'
docs_dir: docs
site_dir: site

# repository information
repo_name: 'Cynthia AKA zzcy'
repo_url: 'https://github.com/whocarsCynthia/whocarsCynthia.github.io'

# copyright
copyright: Copyright <span style="font-family:Arial;">&copy;</span> 2025-2026 <a href="https://github.com/whocarsCynthia" target="_blank">Cynthia</a>

use_directory_urls: true

# configuration
theme:
  name: material
  logo: logo.ico  # 修改为实际路径
  favicon: logo.ico
  custom_dir: overrides
  icon: 
    admonition:
      note: octicons/book-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/alarm-multiple
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      important: octicons/tag-16

  features:
  # navigation
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.path  
    - navigation.top  
    - navigation.footer  
    - navigation.instant
  # serch
    - search.highlight
    - search.suggest

  # content
    - toc.follow
    - toc.integrate
    - content.toc
    - content.code.annotate  
    - content.code.copy  
    - content.tabs.link 
    - content.code.select
  
  language: 'zh'

  palette:
    - scheme: default
      primary: white  # 主色调
      accent: indigo   # 强调色
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: 深色模式


markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - abbr  # 支持缩写
  - admonition  # 支持警告框
  - attr_list  # 允许为Markdown元素添加HTML属性
  - def_list  # 支持定义列表
  - md_in_html  # 支持在HTML中使用Markdown
  - tables  # 支持表格
  - mdx_truly_sane_lists # 嵌套列表（需要pip安装）
  - admonition
  
  # 目录生成
  - toc:
      permalink: true
      toc_depth: 3
      permalink_title: "anchor link to this section for reference"  # 永久链接标题
  - markdown.extensions.smarty:
      smart_quotes: false  # 关闭智能引号

  # 公式渲染
  - pymdownx.arithmatex:
      generic: true  # 支持内联和块级数学公式，使用MathJax渲染
      # block_tag: 'pre'  # 使用<pre>标签包裹块级公式
  
  # 代码相关
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
       preserve_tabs: true  # 保留制表符
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  # Mermaid图表
        - name: card-grid
          class: card-grid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: card-carousel
          class: card-carousel
          format: !!python/name:pymdownx.superfences.fence_code_format
        #- name: math
        #  class: arithmatex
         # format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format  # 数学公式

  # 扩展mk语法
  - pymdownx.critic
  - pymdownx.caret  # 支持插入符号（^）表示上标
  - pymdownx.emoji:
      # emoji_index: !!python/name:pymdownx.emoji.twemoji
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji  # 使用Twemoji索引
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  # 使用SVG生成Emoji
  - pymdownx.magiclink:
      repo_url_shorthand: true  # 使用简写形式的仓库链接
      repo_url_shortener: true  # 缩短仓库链接
      social_url_shorthand: true  # 社交链接简写
      social_url_shortener: true  # 社交链接缩短
  - pymdownx.mark  # 提供文本高亮功能
  - pymdownx.smartsymbols  # 自动将特定文本符号转换为对应的智能符号
  - pymdownx.tasklist:
      custom_checkbox: true  # 允许创建自定义风格的任务列表
  - pymdownx.tilde  # 使用波浪线（~）表示删除线
  - pymdownx.keys

  # 文档布局与样式
  - pymdownx.details  # 允许添加可展开的详细信息块
  - pymdownx.tabbed:
      alternate_style: true  # 使用备用样式的标签式布局
  - pymdownx.keys  # 支持按键表示
  - pymdownx.escapeall:
      hardbreak: True  # 硬换行
      nbsp: True  # 不断行空格
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # 其他功能
  - pymdownx.progressbar  # 支持进度条
  - pymdownx.striphtml  # 去除HTML标签
  - pymdownx.saneheaders  # 优化标题解析，避免冲突
  - attr_list

extra_css:
  - css/custom.css
  - css/counter.css
  - css/toc.css
  - css/flink.css
  - css/extra.css
  - css/process_tracker.css
  - css/entertain.css
  - https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap
  - https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;700&display=swap
  

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/toc.js
  - javascripts/MathJax-3.2.2/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/extra.js
  - javascripts/image-path.js
  - javascripts/tracker.js
  - javascripts/entertain.js
  # - https://polyfill.alicdn.com/polyfill.min.js?features=es6

nav:
  - Home: index.md
  - 生活访问: 
      - Guide: life/guide.md
      - Tracking: life/track.md  
      - Entertainment: life/entertain.md     

  - 牛马手记: 
      - Abstract: work/fore.md
      - Internship: work/intern.md
      - Interview: work/interview.md
      - CV Assistant: work/cv.md

  - 校园游荡: 
      - Abstract: college/fore.md
      - Course Evaluation: college/course.md
      - Major Overview: college/major.md
      - Courses Note: 
          - 计量经济学: college/core/jl.md
          - 大数据经济学: college/core/dsj.md
      - Related Competiton: college/competition.md
      - Study Abroad: college/abroad.md

  - 知识囤货: 
      - Abstract: study/foreword.md
      - Japanese: study/japanese.md
      - DataBase & SQL: study/sql.md
      - Business Operation: study/businessop.md

  - 人格探索: 
      - Tests: privacy/test.md

  - 脑洞发散: 
      - 素材: write/material.md
      - 灵感: write/idea.md
      - 随笔: write/jotting.md
      - 练习: write/practice.md
  
  
  
plugins:

  # meta
  - search:
      lang:
        - zh
        - en
        - ja
      separator: '[\s\u200b\-]'
  
  # heti插件
  # @https://github.com/TonyCrane/mkdocs-heti-plugin
  - heti:
      disable_serve: false
  
  # https://github.com/TonyCrane/mkdocs-statistics-plugin
  - statistics:
      words_per_minute: 256
      codelines_per_minute: 80
  
  # 显示文件的最后修改时间，基于git提交记录
    # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  # - git-revision-date-localized:
      #type: datetime
      #timezone: Asia/Shanghai
      #locale: zh
      #enable_creation_date: true
      #enable_git_follow: true
      #exclude:
        #- index.md
      #strict: false

  - document-dates:
      position: bottom            # 显示位置：top（标题后） bottom（文档末尾），默认：bottom
      type: date              # 时间类型：date datetime timeago，默认：date
      locale: zh               # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      #date_format: '%Y-%m-%d'  # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      #time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      exclude:                 # 排除文件列表，默认为空
        - index.md              # 排除指定文件
        #- private/*            # 排除 private 目录下所有文件，包括子目录
      show_author: false        # 是否显示作者信息，默认：true

  
  # 支持jupyter notebook
  - mkdocs-jupyter:
      execute: true
      kernel_name: python3
      theme: dark
      include_source: True
      custom_mathjax_url: "/style/javascripts/MathJax-3.2.2/es5/tex-mml-chtml.js"
  
  # 支持视频
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"    
  